base_url = "https://clip-template.vercel.app"
[book]
title = "Cainanyang's Clip"
description = "Cainanyang's Clip"
src = "content"
language = "zh"
authors = ["Cainanyang"]

[output.html]
git-repository-url = "https://github.com/cainanyang/clip"
edit-url-template = "https://github.com/cainanyang/clip/edit/main/{path}"

[output.html.search]
enable = false

[output.markdown]
enable = true

[mail]
# false will diasble mail sending
enable = false
from_email = "cainanyang@gmail.com"
from_name = "cainanyang"
# you can set the mailjet contact list id here
# mailjet_contact_list_id = "17669"
# or directly set the to_email, seperated by comma
# or your can also set the environment variable TO_EMAIL
to_email = ""
